version: "1.0"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    environment:
      - ZOOKEEPER_CLIENT_PORT= 2181
  kafka:
    image: confluentinc/cp-kafka
    depends_on:
      - zookepeer
    environment:
      - KAFKA_ZOOKEEPER_CONNECT = zoopeeker:2181
      - KAFKA_ADVERTISED_LISTENERS =  PLAINTEXT://kafka:29092, PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP = PLAINTEXT:PLAINTEXT, PLAINTEXT_HOST:PLAINTEXT
    ports:
      - 9092:9092